

//Prefix
export const PREFIX_LOADING="_LOADING";
export const PREFIX_OK="_OK";
export const PREFIX_FAILED="_FAILED";
export const PREFIX_TIME_OUT="_TIME_OUT";


export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_OK = 'FETCH_QUESTIONS_OK';
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED';
export const FETCH_QUESTIONS_TIME_OUT = 'FETCH_QUESTIONS_TIME_OUT';
export const LOAD_HOMEPAGE = "LOAD_HOMEPAGE";
export const LOAD_HOMEPAGE_OK = 'LOAD_HOMEPAGE_OK';
export const LOAD_HOMEPAGE_FAILED = 'LOAD_HOMEPAGE_FAILED';
export const LOAD_HOMEPAGE_TIME_OUT = 'LOAD_HOMEPAGE_TIME_OUT';
export const LOAD_MAINBOX = "LOAD_MAINBOX";
export const LOAD_MAINBOX_OK = 'LOAD_MAINBOX_OK';
export const LOAD_MAINBOX_FAILED = 'LOAD_MAINBOX_FAILED';
export const LOAD_MAINBOX_TIME_OUT = 'LOAD_MAINBOX_TIME_OUT';

