//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudyWebAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Answer
    {
        public int id { get; set; }
        public Nullable<int> answerId { get; set; }
        public Nullable<int> questionId { get; set; }
        public Nullable<bool> isCorrect { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
    }
}
