//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudyWebAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourses_Lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCourses_Lessons()
        {
            this.User_Lesson_Course = new HashSet<User_Lesson_Course>();
        }
    
        public int id { get; set; }
        public int course_id { get; set; }
        public int lesson_id { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual tblLesson tblLesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Lesson_Course> User_Lesson_Course { get; set; }
    }
}
