//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudyWebAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLesson()
        {
            this.Question_Lesson = new HashSet<Question_Lesson>();
            this.tblCourses_Lessons = new HashSet<tblCourses_Lessons>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string video_link { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Lesson> Question_Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCourses_Lessons> tblCourses_Lessons { get; set; }
    }
}
